# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Mod Information
mod_version = 1.0.0
root_package = com.example
mod_id = modid
mod_name = Mod Name

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Access Transformers (Optional)
use_access_transformer = true

# Coremods (Optional)
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover (Optional)
use_asset_mover = false
asset_mover_version = 2.5
